name: Build and test

on:
  push:
    branches:
      - '**'
  pull_request:
  release:
    types: [published]
  
jobs:
  define-shared-vars:
    runs-on: ubuntu-latest
    outputs:
      GIT_TAG: ${{ steps.variables.outputs.GIT_TAG }}
      GIT_BRANCH: ${{ steps.variables.outputs.GIT_BRANCH }}
      OUTPUT_DIR: ${{ steps.variables.outputs.OUTPUT_DIR }}
    steps:
      -
        name: Set variables needed in all jobs
        id: variables
        run: |
          GIT_TAG=${{ github.event.release.tag_name }}
          # If GIT_TAG is set then GIT BRANCH should be "master", else set it from GITHUB_REF
          GIT_BRANCH=$([ -n "${GIT_TAG}" ] && echo "master" || echo "${GITHUB_REF#refs/*/}")

          echo ::set-output name=GIT_BRANCH::${GIT_BRANCH}
          echo ::set-output name=GIT_TAG::${GIT_TAG}
          echo ::set-output name=OUTPUT_DIR::${GIT_TAG:-${GIT_BRANCH}}
  job2:
    runs-on: ubuntu-latest
    needs: define-shared-vars
    steps:
     - 
       name: Test?
       run: |
        echo ${{define-shared-vars.outputs.GIT_TAG}}
        echo ${{define-shared-vars.outputs.GIT_BRANCH}}
        echo ${{define-shared-vars.outputs.OUTPUT_DIR}}
  job3:
    runs-on: ubuntu-latest
    needs: define-shared-vars
    env:
     BUM: ${{needs.define-shared-vars.outputs.GIT_TAG}}
     BUM2: ${{needs.define-shared-vars.outputs.GIT_BRANCH}}
     BUM3: ${{needs.define-shared-vars.outputs.OUTPUT_DIR}}
    steps:
     - 
       name: Test?
       run: |
          echo ${BUM} 
          echo ${BUM2}
          echo ${BUM3}
       
    
