name: Build and test

on:
  push:
    branches:
      - '**'
  pull_request:
  release:
    types: [published]
    
env:
  GIT_TAG: ${{ github.event.release.tag_name }}
  GIT_BRANCH: ${GITHUB_REF#refs/*/}
  OUTPUT_DIR: ${GIT_TAG:-${GIT_BRANCH}}

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      -
        name: Test
        run: |
          GIT_TAG=${{ github.event.release.tag_name }}
          # If GIT_TAG is set then GIT BRANCH should be "master", else set it from GITHUB_REF
          GIT_BRANCH=$([ -n "${GIT_TAG}" ] && echo "master" || echo "${GITHUB_REF#refs/*/}")
          OUTPUT_DIR=${GIT_TAG:-${GIT_BRANCH}}
          
          echo "GIT_TAG=${GIT_TAG}" >> $GITHUB_ENV
          echo "GIT_BRANCH=${GIT_BRANCH}" >> $GITHUB_ENV
          echo "OUTPUT_DIR=${OUTPUT_DIR}" >> $GITHUB_ENV
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
     - 
       name: Test?
       run: |
          echo ${GIT_TAG}
          echo ${GIT_BRANCH}
          echo ${OUTPUT_DIR}
  job3:
    runs-on: ubuntu-latest
    needs: job2
    steps:
     - 
       name: Test?
       run: |
          echo ${GIT_TAG}
          echo ${GIT_BRANCH}
          echo ${OUTPUT_DIR}
       
    
