name: Build and test

on:
  push:
    branches:
      - '**'
  pull_request:
  release:
    types: [published]

jobs:
  define-shared-vars:
    runs-on: ubuntu-latest   
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Release
        uses: softprops/action-gh-release@v1
        if: ${{ github.event_name == 'release' }}
        with:
          files: |
            *
