name: Build and test

on:
  push:
    branches:
      - '**'
  pull_request:
  release:
    types: [published]

env:
  GIT_TAG: ${{ github.event.release.tag_name }}
  GIT_BRANCH: ${GITHUB_REF#refs/*/}
  OUTPUT_DIR: ${GIT_TAG:-${GIT_BRANCH}}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      -
        name: Test
        run: |
          echo ${GIT_TAG}
          echo ${GIT_BRANCH}
          echo ${OUTPUT_DIR}
    
